baseapp/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from baseapp.views import Home
from analizaproveedor.views import AnalizaProveedor
from buscapatrones.views import BuscaPatrones

urlpatterns = [
    path('', Home, name='home'),
    path('/analizaproveedor', AnalizaProveedor, name='analizaproveedor'),
    path('/buscapatrones', BuscaPatrones, name='buscapatrones'),

]

iacompraspublicas/urls.py
from django.contrib import admin
from django.urls import path, include
from baseapp import urls
from cargainfo import urls
from analisiscompraspublicas import urls

urlpatterns = [
    path('', include(('baseapp.urls', 'baseapp'), namespace="baseapp")),
    path('ia/', include(('analisiscompraspublicas.urls', 'analisiscompraspublicas'), namespace="analisiscompraspublicas")),
    path('ci/', include(('cargainfo.urls', 'cargainfo'), namespace="cargainfo")),
    
    # path('admin/', admin.site.urls),
    # path('admin/', admin.site.urls),
]

templates/base/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

{% block title %}
{% endblock title %}
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	{% block descripcion_autor %}
	<meta name="description" content="">
    <meta name="author" content="">
	<link rel="" type="" size="32x32" href="#"></link>
	{% endblock descripcion_autor %}

	<!-- FontAwesome JS-->
	<script defer src="{% static 'assets/plugins/fontawesome/js/all.min.js' %}"></script>
	<!-- App CSS -->
	<link id="theme-style" rel="stylesheet" href="{% static 'assets/css/portal.css' %}">

	{% block csstables %}
    {% endblock  %}
   <!-- Custom styles for this page
   <link href="{% static 'assets/vendor/datatables/dataTables.bootstrap4.min.css'%}" rel="stylesheet">-->
     <!-- jQuery Confirm -->
  <link rel="stylesheet" href="{% static 'assets/vendor/jquery_confirm/jquery-confirm.min.css' %}">

  <!-- XDSoft DateTimePicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
            integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />

  <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/css/select2.min.css" rel="stylesheet" />

  <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/css/select2.min.css" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

</head>

<body class="app">
    <header class="app-header fixed-top">
        <div class="app-header-inner">
	        <div class="container-fluid py-2">
		        <div class="app-header-content">
		            <div class="row justify-content-between align-items-center">
				    <div class="col-auto">
					    <a id="sidepanel-toggler" class="sidepanel-toggler d-inline-block d-xl-none" href="#">
						    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" role="img">
							<title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg>
					    </a>
				    </div><!--//col-->
		            <div class="app-utilities col-auto">
			            <div class="app-utility-item app-user-dropdown dropdown">
				            <a class="dropdown-toggle" id="user-dropdown-toggle"
								data-bs-toggle="dropdown" href="#"
								role="button" aria-expanded="false">
							</a>
							<img src="{% static 'assets/images/user.png' %}" alt="Bienvenido">
				            <ul class="dropdown-menu" aria-labelledby="user-dropdown-toggle">
								<!--<li><a class="dropdown-item" href="account.html">Account</a></li>
								<li><a class="dropdown-item" href="settings.html">Settings</a></li>n-->
								<li><hr class="dropdown-divider"></li>
								<li><a class="dropdown-item" href="#">Salir</a></li>
							</ul>
			            </div><!--//app-user-dropdown-->
		            </div><!--//app-utilities-->
	            </div><!--//app-header-content-->
	        </div><!--//container-fluid-->
        </div><!--//app-header-inner-->
        <div id="app-sidepanel" class="app-sidepanel">
	        <div id="sidepanel-drop" class="sidepanel-drop"></div>
	        <div class="sidepanel-inner d-flex flex-column">
		        <a href=" {% url 'baseapp:home' %} " id="sidepanel-close" class="sidepanel-close d-xl-none">&times;</a>
		        <div class="app-branding">
		            <a class="app-logo" href=" {% url 'baseapp:home' %} ">
						<img class="logo-icon me-2" src="{% static 'assets/images/logo.png' %}" alt="logo">
						{% block logo_text %}
						<span class="logo-text"></span></a>
						{% endblock logo_text %}
		        </div><!--//app-branding-->
		        <hr class="dropdown-divider">
			    <nav id="app-nav-main" class="app-nav app-nav-main flex-grow-1">
					{% block app_menu %}
					<ul class="app-menu list-unstyled accordion" id="menu-accordion">
					</ul><!--//app-menu-->
					{% endblock app_menu %}
			    </nav><!--//app-nav-->
	        </div><!--//sidepanel-inner-->
	    </div><!--//app-sidepanel-->
    </header>

    <div class="app-wrapper">
		{% block dashboard %}
		{% endblock dashboard %}

	    {% block page_content %}
		{% endblock %}
		<!--//app-header

	    -->
	    <footer class="app-footer">
		    <div class="container text-center py-3">
		         <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
		    </div>
	    </footer><!--//app-footer-->

    </div><!--//app-wrapper-->
	<!--
	<div class="modal fade" id="popup"></div>
    -->
	<!-- Javascript -->
    <script src="{% static 'assets/plugins/popper.min.js'%}"></script>
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js'%}"></script>

	<!-- Charts JS -->
	<!-- <script src="{% static 'assets/js/chart.js'%}"></script> -->
	<script src="{% static 'assets/plugins/chart.js/chart.min.js'%}"></script>
	<!-- <script src="{% static 'assets/js/index-charts.js'%}"></script> -->

    <!-- Page Specific JS -->
    <script src="{% static 'assets/js/app.js'%}"></script>

	<!-- Page level plugins -->
	<script src="{% static 'assets/vendor/datatables/jquery.dataTables.min.js'%}"></script>
	<script src="{% static 'assets/vendor/datatables/dataTables.bootstrap4.min.js'%}"></script>

	<!-- Bootstrap core JavaScript-->
	<script src="{% static 'assets/vendor/jquery/jquery.min.js'%}"></script>
	<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

	<!-- Core plugin JavaScript-->
	<script src="{% static 'assets/vendor/jquery-easing/jquery.easing.min.js'%}"></script>

	<script src="{% static 'assets/vendor/jquery_confirm/jquery-confirm.min.js'%}"></script>

	<script src="{% static  'assets/vendor/js/jquery.chained.min.js' %}"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
	<!-- Popperjs -->
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
	crossorigin="anonymous"></script>
	<!-- Tempus Dominus JavaScript -->
	<script src="https://cdn.jsdelivr.net/gh/Eonasdan/tempus-dominus@master/dist/js/tempus-dominus.js"
	crossorigin="anonymous"></script>

	<!-- Tempus Dominus Styles -->
	<link href="https://cdn.jsdelivr.net/gh/Eonasdan/tempus-dominus@master/dist/css/tempus-dominus.css"
	rel="stylesheet" crossorigin="anonymous">

<script>
	$('#btn_procesar').click(function(){
		alert("Archivo procesado");
	});
</script>
	<script>
		$(document).ready(function () {
		  jQuery.datetimepicker.setLocale('es');
		  format: 'd/m/Y'
		  timepicker: false
		});
	</script>

  	<script type="text/javascript">
        $(function(){
            $("#datetime").datetimepicker({
                format: 'd/m/Y',
                timepicker:false
            });
        });
	</script>
	<script type="text/javascript">
	$(function(){
		$("#f1, #f2").datetimepicker({
			format: 'Y-m-d',
			timepicker:false
		});

		$("#btnPrint").click(function(e){
			e.preventDefault();
			var f1,f2;
			f1 = $("#f1").val();
			f2 = $("#f2").val();
			if(f1=="" || f1==null){
				var d1 = new Date();
				var f2 = d1.getFullYear() + "-" + (d1.getMonth()+1) + "-" + d1.getDate();
			}
			if(f2=="" || f2==null){
				var d = new Date();
				var f2 = d.getFullYear() + "-" + (d.getMonth()+1) + "-" + d.getDate();
			}

			var url = "imprimir-todas/" + f1 + "/" + f2;

			window.open(url,'facturas');
		});
	});
	</script>
	<!-- <script src="{% static 'assets/vendor/bootstrap/js/bootstrap-datetimepicker.min.js'%}"></script>-->
	{% block control_modal%}
		<script>
			function abrir_modal(url)
			{

				$("#popup").load(url, function(){
				$(this).modal({
					backdrop:'static',
					keyboard: false
				})
				$(this).modal('show');
				});
				return false;
			}

			function cerrar_modal()
			{
				$('#popup').modal('hide');
				return false;
			}

			function mensaje(msg,color='green')
			{
				if (color=="success")
				{
				color="green";
				}
				if (color=="error")
				{
				color="red";
				}


				$.alert({
				title:'',
				theme:'material',
				type:color,
				content:msg
				});
			}

			{% if messages %}
				{% for message in messages %}
				console.log("{{ message.tags }}");
				mensaje("{{ message }}","{{ message.tags }}");
				{% endfor %}
			{% endif %}

		</script>
	{% endblock control_modal %}

	{% block js_tablas %}

	{% endblock %}

	{% block js_page %}

	{% endblock %}

	{% block js_graficos %}
	{% endblock js_graficos%}
</body>
</html>