analisiscompraspublicas/urls.py
from django.urls import path, include
from analisiscompraspublicas.views import contratosView, compradoresView, compradores2View, \
                                        proveedoresView, analisisvariosView, tendencia_contratos, \
                                        grafico_arima, tendencia_valor_contrato
                                        

urlpatterns = [
    path('contratos', contratosView, name="contratosView"),
    path('compradores', compradoresView, name="compradoresView"),
    path('compradores2', compradores2View, name="compradores2View"),
    path('proveedores', proveedoresView, name="proveedoresView"),
    path('analisisvarios', analisisvariosView, name="analisisvariosView"),



    path('aivarios/', tendencia_contratos, name="tendencia_contratos"),
    path('aivarios2/', grafico_arima, name="grafico_arima"),
    path('aivarios3/', tendencia_valor_contrato, name="tendencia_valor_contrato"),


]

baseapp/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from baseapp.views import Home
from analizaproveedor.views import AnalizaProveedor
from buscapatrones.views import BuscaPatrones

urlpatterns = [
    path('', Home, name='home'),
    path('/analizaproveedor', AnalizaProveedor, name='analizaproveedor'),
    path('/buscapatrones', BuscaPatrones, name='buscapatrones'),

]

cargainfo/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from cargainfo.views import CargaInfoView

urlpatterns = [
    path('cargainfo', CargaInfoView, name='cargainfo'),

]

iacompraspublicas/urls.py
from django.contrib import admin
from django.urls import path, include
from baseapp import urls
from cargainfo import urls
from analisiscompraspublicas import urls

urlpatterns = [
    path('', include(('baseapp.urls', 'baseapp'), namespace="baseapp")),
    path('ia/', include(('analisiscompraspublicas.urls', 'analisiscompraspublicas'), namespace="analisiscompraspublicas")),
    path('ci/', include(('cargainfo.urls', 'cargainfo'), namespace="cargainfo")),
    
    # path('admin/', admin.site.urls),
    # path('admin/', admin.site.urls),
]

baseapp/models.py
from io import open_code
from unicodedata import name
from django.db import models


class solicitud_compra:
    ocid = models.CharField(max_length=250)
    release_id = models.CharField(max_length=250)
    id = models.CharField(max_length=250)
    awardID = models.CharField(max_length=250)
    title = models.CharField(max_length=250)
    description = models.CharField(max_length=250)
    status = models.CharField(max_length=250)
    contractPeriod_startDate = models.DateField(blank=True, null=True)
    contractPeriod_endDate = models.DateField(blank=True, null=True)
    contractPeriod_maxExtentDate = models.CharField(max_length=250)
    contractPeriod_durationInDays = models.CharField(max_length=250)
    amount = models.CharField(max_length=250)
    currency = models.CharField(max_length=250)
    dateSigned = models.DateField(blank=True, null=True)

    def __str__(self):
        return '{}:{}'.format(self.ocid, self.title)

    def save(self):
        self.ocid = self.ocid
        self.release_id = self.release_id
        self.id = self.id
        self.awardID = self.awardID
        self.title = self.title
        self.description = self.description
        self.status = self.status
        self.contractPeriod_startDate = self.contractPeriod_startDate
        self.contractPeriod_endDate = self.contractPeriod_endDate
        self.contractPeriod_maxExtentDate = self.contractPeriod_maxExtentDate
        self.contractPeriod_durationInDays = self.contractPeriod_durationInDays
        self.amount = self.amount
        self.currency = self.currency
        self.dateSigned = self.dateSigned
        super(solicitud_compra, self).save()

    class Meta:
        verbose_name_plural = "solicitud_compras"
        db_table = 'solicitud_compra'


class sri_ente:
    numero_ruc = models.CharField(max_length=250)
    razon_social = models.CharField(max_length=250)
    provincia_jurisdiccion = models.CharField(max_length=250)
    nombre_comercial = models.CharField(max_length=250)
    estado_contribuyente = models.CharField(max_length=250)
    clase_contribuyente = models.CharField(max_length=250)
    fecha_inicio_actividades = models.DateField(blank=True, null=True)
    fecha_actualizacion = models.DateField(blank=True, null=True)
    fecha_suspension_definitiva = models.DateField(blank=True, null=True)
    fecha_reinicio_actividades = models.DateField(blank=True, null=True)
    obligado = models.CharField(max_length=250)
    tipo_contribuyente = models.CharField(max_length=250)
    numero_establecimiento = models.CharField(max_length=250)
    nombre_fantasia_comercial = models.CharField(max_length=250)
    estado_establecimiento = models.CharField(max_length=250)
    descripcion_provincia_est = models.CharField(max_length=250)
    descripcion_canton_est = models.CharField(max_length=250)
    descripcion_parroquia_est = models.CharField(max_length=250)
    codigo_ciiu = models.CharField(max_length=250)
    actividad_economica = models.CharField(max_length=250)

    def __str__(self):
        return '{}:{}'.format(self.nombre, self.lote)

    def save(self):
        self.numero_ruc = self.numero_ruc
        self.razon_social = self.razon_social
        self.provincia_jurisdiccion = self.provincia_jurisdiccion
        self.nombre_comercial = self.nombre_comercial
        self.estado_contribuyente = self.estado_contribuyente
        self.clase_contribuyente = self.clase_contribuyente
        self.fecha_inicio_actividades = self.fecha_inicio_actividades
        self.fecha_actualizacion = self.fecha_actualizacion
        self.fecha_suspension_definitiva = self.fecha_suspension_definitiva
        self.fecha_reinicio_actividades = self.fecha_reinicio_actividades
        self.obligado = self.obligado
        self.tipo_contribuyente = self.tipo_contribuyente
        self.numero_establecimiento = self.numero_establecimiento
        self.nombre_fantasia_comercial = self.nombre_fantasia_comercial
        self.estado_establecimiento = self.estado_establecimiento
        self.descripcion_provincia_est = self.descripcion_provincia_est
        self.descripcion_canton_est = self.descripcion_canton_est
        self.descripcion_parroquia_est = self.descripcion_parroquia_est
        self.codigo_ciiu = self.codigo_ciiu
        self.actividad_economica = self.actividad_economica 
        super(sri_ente, self).save()

    class Meta:
        verbose_name_plural = "sri_entes"
        db_table = 'sri_ente'

baseapp/views.py
from django.shortcuts import render

# Create your views here.

#vista de home
def Home(request):
    template_name = 'baseapp/home.html'
    return render(request, template_name)

baseapp/templates/baseapp/home.html
{% extends 'base/home.html' %}
{% load static %}
{% block title %}
    <title>IAHackaton</title>
{% endblock title %}
{% block descripcion_autor %}
<meta name="description" content="Aplicación para ayudar en compras públicas">
<meta name="author" content="wlopezc-mgomez">
<link rel="icon" type="image/png" size="32x32" href="{% static 'assets/images/favicon-32x32.png' %}"></link>
{% endblock descripcion_autor %}


{% block csstables %}
<style media="print">
imprimir { display: block;}
.seccion {
    font-family: Arial, sans-serif;
    font-size: 14px;
    line-height: 1.5;
    padding: 10px;
    background-color: #f2f2f2;
}
</style>
  <!-- Custom fonts for this template -->
  <link href="{% static 'assets/vendor/fontawesome-free/css/all.min.css'%}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'assets/vendor/css/sb-admin-2.min.css'%}" rel="stylesheet">

  
   <!-- Custom styles for this page -->
   <link href="{% static 'assets/vendor/datatables/dataTables.bootstrap4.min.css'%}" rel="stylesheet">
     <!-- jQuery Confirm -->
  <link rel="stylesheet" href="{% static 'assets/vendor/jquery_confirm/jquery-confirm.min.css' %}">

  <!-- XDSoft DateTimePicker -->  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" 
            integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />  

  <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/css/select2.min.css" rel="stylesheet" />

{% endblock csstables %}

{% block dashboard %}
{% endblock dashboard%}

{% block logo_text %}
<span class="logo-text">IAHackaton</span></a>
{% endblock logo_text %}

{% block app_menu %}
<ul class="app-menu list-unstyled accordion" id="menu-accordion">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'analisiscompraspublicas:contratosView' %}">
                <span class="nav-link-text">Contratos</span>
        </a><!--//nav-link-->
    </li><!--//nav-item-->
    <li class="nav-item">
        <a class="nav-link" href="{% url 'analisiscompraspublicas:compradoresView' %}">
                <span class="nav-link-text">Licitaciones</span>
        </a><!--//nav-link-->
    </li><!--//nav-item-->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'analisiscompraspublicas:compradores2View' %}">
              <span class="nav-link-text">Licitaciones por categorías</span>
      </a><!--//nav-link-->
    </li><!--//nav-item-->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'analisiscompraspublicas:proveedoresView' %}">
              <span class="nav-link-text">Proveedores</span>
      </a><!--//nav-link-->
    </li><!--//nav-item-->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'analisiscompraspublicas:analisisvariosView' %}">
              <span class="nav-link-text">Varios</span>
      </a><!--//nav-link-->
    </li><!--//nav-item-->


    <li class="nav-item">
        <a class="nav-link" href= {% url 'cargainfo:cargainfo' %}>
                <span class="nav-link-text">Carga información (OCDS) :: en base desde el 21 al 23</span>
        </a><!--//nav-link-->        
    </li><!--//nav-item-->
</ul><!--//app-menu-->
{% endblock app_menu %}



{% block page_content %}

{% endblock page_content %}

{% block js_tablas %}
	<!-- Page level plugins -->
	<script src="{% static 'assets/vendor/datatables/jquery.dataTables.min.js'%}"></script>
	<script src="{% static 'assets/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

	<!-- Bootstrap core JavaScript-->
	<script src="{% static 'assets/vendor/jquery/jquery.min.js'%}"></script>
	<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

	<!-- Core plugin JavaScript-->
	<script src="{% static 'assets/vendor/jquery-easing/jquery.easing.min.js'%}"></script>

	<!-- Page level custom scripts -->
	<script src="{% static 'assets/vendor/js/demo/datatables-demo.js'%}"></script>
{% endblock js_tablas %}


{% block js_page %}
<script>
  var jq = jQuery.noConflict(true);
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
<script src="{% static 'assets/js/chart.js'%}"></script>
<script src="{% static 'assets/js/chart.min.js'%}"></script>  
<script src="{% static 'assets/js/index-charts.js'%}"></script>
{% endblock %}

{% block js_graficos %}
{% endblock js_graficos%}
 